# Generated by Django 4.0.1 on 2022-06-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], max_length=1)),
                ('definition', models.TextField()),
                ('link', models.URLField()),
                ('correct_tally', models.IntegerField()),
                ('incorrect_tally', models.IntegerField()),
            ],
        ),
    ]
